FROM linuxserver/code-server:latest

# install dependencies
RUN apt-get update && \ 
    apt-get install -y libicu-dev ca-certificates curl apt-transport-https lsb-release gnupg && \ 
    rm -rf /var/lib/apt/lists/*

# install Azure CLI and Azure bicep
RUN curl -sL https://aka.ms/InstallAzureCLIDeb | bash && \
    curl -Lo bicep https://github.com/Azure/bicep/releases/latest/download/bicep-linux-$(dpkg --print-architecture) && \
    chmod +x bicep && \
    mv bicep /usr/local/bin/bicep

# Install extensions and themes
RUN /app/code-server/bin/code-server --install-extension ms-vscode.azure-account && \
    /app/code-server/bin/code-server --install-extension ms-vscode.azurecli && \
    /app/code-server/bin/code-server --install-extension ms-azuretools.vscode-docker && \
    /app/code-server/bin/code-server --install-extension yzhang.markdown-all-in-one && \
    /app/code-server/bin/code-server --install-extension DavidAnson.vscode-markdownlint && \
    /app/code-server/bin/code-server --install-extension ms-vscode.powershell && \
    /app/code-server/bin/code-server --install-extension esbenp.prettier-vscode && \
    /app/code-server/bin/code-server --install-extension redhat.vscode-yaml && \
    /app/code-server/bin/code-server --install-extension GitHub.github-vscode-theme && \
    curl -Lo /tmp/rosshamish.kuskus-kusto-syntax-highlighting.vsix https://marketplace.visualstudio.com/_apis/public/gallery/publishers/rosshamish/vsextensions/kuskus-kusto-syntax-highlighting/latest/vspackage && \
    curl -Lo /tmp/bencoleman.armview.vsix https://marketplace.visualstudio.com/_apis/public/gallery/publishers/bencoleman/vsextensions/armview/0.4.6/vspackage && \
    curl -Lo /tmp/azurepolicy.azurepolicyextension.vsix https://marketplace.visualstudio.com/_apis/public/gallery/publishers/AzurePolicy/vsextensions/azurepolicyextension/0.2.2/vspackage && \
    curl -Lo /tmp/ms-azuretools.vscode-bicep.vsix https://marketplace.visualstudio.com/_apis/public/gallery/publishers/ms-azuretools/vsextensions/vscode-bicep/0.12.40/vspackage && \
    /app/code-server/bin/code-server --install-extension /tmp/rosshamish.kuskus-kusto-syntax-highlighting.vsix  && \
    /app/code-server/bin/code-server --install-extension /tmp/bencoleman.armview.vsix && \
    /app/code-server/bin/code-server --install-extension /tmp/azurepolicy.azurepolicyextension.vsix  && \
    /app/code-server/bin/code-server --install-extension /tmp/ms-azuretools.vscode-bicep.vsix  && \
    rm /tmp/*.vsix && \
    mkdir /config/extensions && \
    mv /config/.local/share/code-server/extensions/* /config/extensions/

# adjust command prompt for root and the main user - see https://github.com/linuxserver/docker-openvscode-server/blob/61efb20cae1fd9562dc66c7b255f9b8cb23df74f/root/etc/cont-init.d/30-config#L21
RUN sed -i "s/    PS1.*/    PS1=\'\\\\w\\\\$ \'/g" /root/.bashrc
