FROM linuxserver/code-server:latest

# install dependencies
RUN apt-get update && \ 
    apt-get install -y libicu-dev ca-certificates curl apt-transport-https lsb-release gnupg gpg wget && \ 
    wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg && \
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list && \
    apt-get update && \ 
    apt-get install -y terraform && \
    rm -rf /var/lib/apt/lists/*

# install Azure CLI and Azure bicep
# RUN curl -sL https://aka.ms/InstallAzureCLIDeb | bash && \
#     curl -Lo bicep https://github.com/Azure/bicep/releases/latest/download/bicep-linux-$(dpkg --print-architecture) && \
#     chmod +x bicep && \
#     mv bicep /usr/local/bin/bicep

# Install extensions and themes
RUN /app/code-server/bin/code-server --install-extension ms-vscode.azure-account && \
    /app/code-server/bin/code-server --install-extension ms-azuretools.vscode-docker && \
    /app/code-server/bin/code-server --install-extension yzhang.markdown-all-in-one && \
    /app/code-server/bin/code-server --install-extension davidanson.vscode-markdownlint && \
    /app/code-server/bin/code-server --install-extension ms-vscode.powershell && \
    /app/code-server/bin/code-server --install-extension esbenp.prettier-vscode && \
    /app/code-server/bin/code-server --install-extension redhat.vscode-yaml && \
    /app/code-server/bin/code-server --install-extension github.github-vscode-theme && \
    /app/code-server/bin/code-server --install-extension akamud.vscode-theme-onedark && \
    /app/code-server/bin/code-server --install-extension janisdd.vscode-edit-csv && \
    /app/code-server/bin/code-server --install-extension hashicorp.terraform && \
    /app/code-server/bin/code-server --install-extension 4ops.terraform && \
    /app/code-server/bin/code-server --install-extension github.vscode-github-actions && \
    /app/code-server/bin/code-server --install-extension ecmel.vscode-html-css && \
    /app/code-server/bin/code-server --install-extension zignd.html-css-class-completion && \
    /app/code-server/bin/code-server --install-extension pkief.material-icon-theme

# Failed extensions
    # ms-azuretools.vscode-bicep
    # josin.kusto-syntax-highlighting
    # matheusq94.tfs
    # aykutsarac.jsoncrack-vscode
    # ms-vscode-remote.remote-ssh
    # ms-vscode-remote.remote-ssh-edit
    # ms-vscode.remote-explorer
    # run-at-scale.terraform-doc-sni

# configure extensions
RUN mkdir /config/extensions && \
    mv /config/.local/share/code-server/extensions/* /config/extensions/

# adjust command prompt for root and the main user - see https://github.com/linuxserver/docker-openvscode-server/blob/61efb20cae1fd9562dc66c7b255f9b8cb23df74f/root/etc/cont-init.d/30-config#L21
RUN sed -i "s/    PS1.*/    PS1=\'\\\\w\\\\$ \'/g" /root/.bashrc
